//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Project
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Client.
    /// </summary>
    // *** Start programmer edit section *** (Client CustomAttributes)

    // *** End programmer edit section *** (Client CustomAttributes)
    [AutoAltered()]
    [Caption("Клиенты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ClientE", new string[] {
            "Password as \'Пароль\'",
            "Login as \'Логин\'"})]
    [View("ClientL", new string[] {
            "Password as \'Пароль\'",
            "Login as \'Логин\'"})]
    public class Client : ICSSoft.STORMNET.DataObject
    {
        
        private string fPassword;
        
        private string fLogin;
        
        // *** Start programmer edit section *** (Client CustomMembers)

        // *** End programmer edit section *** (Client CustomMembers)

        
        /// <summary>
        /// Login.
        /// </summary>
        // *** Start programmer edit section *** (Client.Login CustomAttributes)

        // *** End programmer edit section *** (Client.Login CustomAttributes)
        [StrLen(255)]
        public virtual string Login
        {
            get
            {
                // *** Start programmer edit section *** (Client.Login Get start)

                // *** End programmer edit section *** (Client.Login Get start)
                string result = this.fLogin;
                // *** Start programmer edit section *** (Client.Login Get end)

                // *** End programmer edit section *** (Client.Login Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.Login Set start)

                // *** End programmer edit section *** (Client.Login Set start)
                this.fLogin = value;
                // *** Start programmer edit section *** (Client.Login Set end)

                // *** End programmer edit section *** (Client.Login Set end)
            }
        }
        
        /// <summary>
        /// Password.
        /// </summary>
        // *** Start programmer edit section *** (Client.Password CustomAttributes)

        // *** End programmer edit section *** (Client.Password CustomAttributes)
        [StrLen(255)]
        public virtual string Password
        {
            get
            {
                // *** Start programmer edit section *** (Client.Password Get start)

                // *** End programmer edit section *** (Client.Password Get start)
                string result = this.fPassword;
                // *** Start programmer edit section *** (Client.Password Get end)

                // *** End programmer edit section *** (Client.Password Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.Password Set start)

                // *** End programmer edit section *** (Client.Password Set start)
                this.fPassword = value;
                // *** Start programmer edit section *** (Client.Password Set end)

                // *** End programmer edit section *** (Client.Password Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ClientE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientE", typeof(IIS.Project.Client));
                }
            }
            
            /// <summary>
            /// "ClientL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientL", typeof(IIS.Project.Client));
                }
            }
        }
    }
}
