//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Project
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Coupon.
    /// </summary>
    // *** Start programmer edit section *** (Coupon CustomAttributes)

    // *** End programmer edit section *** (Coupon CustomAttributes)
    [AutoAltered()]
    [Caption("Купоны")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CouponE", new string[] {
            "Percent as \'Процент\'",
            "ProductName as \'Название товара\'"})]
    [View("CouponL", new string[] {
            "Percent as \'Процент\'",
            "ProductName as \'Название товара\'"})]
    public class Coupon : ICSSoft.STORMNET.DataObject
    {
        
        private double fPercent;
        
        private string fProductName;
        
        // *** Start programmer edit section *** (Coupon CustomMembers)

        // *** End programmer edit section *** (Coupon CustomMembers)

        
        /// <summary>
        /// Percent.
        /// </summary>
        // *** Start programmer edit section *** (Coupon.Percent CustomAttributes)

        // *** End programmer edit section *** (Coupon.Percent CustomAttributes)
        public virtual double Percent
        {
            get
            {
                // *** Start programmer edit section *** (Coupon.Percent Get start)

                // *** End programmer edit section *** (Coupon.Percent Get start)
                double result = this.fPercent;
                // *** Start programmer edit section *** (Coupon.Percent Get end)

                // *** End programmer edit section *** (Coupon.Percent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Coupon.Percent Set start)

                // *** End programmer edit section *** (Coupon.Percent Set start)
                this.fPercent = value;
                // *** Start programmer edit section *** (Coupon.Percent Set end)

                // *** End programmer edit section *** (Coupon.Percent Set end)
            }
        }
        
        /// <summary>
        /// ProductName.
        /// </summary>
        // *** Start programmer edit section *** (Coupon.ProductName CustomAttributes)

        // *** End programmer edit section *** (Coupon.ProductName CustomAttributes)
        [StrLen(255)]
        public virtual string ProductName
        {
            get
            {
                // *** Start programmer edit section *** (Coupon.ProductName Get start)

                // *** End programmer edit section *** (Coupon.ProductName Get start)
                string result = this.fProductName;
                // *** Start programmer edit section *** (Coupon.ProductName Get end)

                // *** End programmer edit section *** (Coupon.ProductName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Coupon.ProductName Set start)

                // *** End programmer edit section *** (Coupon.ProductName Set start)
                this.fProductName = value;
                // *** Start programmer edit section *** (Coupon.ProductName Set end)

                // *** End programmer edit section *** (Coupon.ProductName Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CouponE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CouponE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CouponE", typeof(IIS.Project.Coupon));
                }
            }
            
            /// <summary>
            /// "CouponL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CouponL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CouponL", typeof(IIS.Project.Coupon));
                }
            }
        }
    }
}
